### ISSUE TITLE
Improve support for Pulumi config overrides

### ISSUE THREAD

**Issue by EronWright** [prepor/github-pulumi#6]
I pass Pulumi config overrides as additional arguments.  Unfortunately I'm not able to use environment variables in those arguments.

The workaround is to use the github actions templating syntax (e.g. `${{ secrets.GCP_PROJECT }}`) but this is inconvenient, e.g. when working with derived values such as image names.

My suggestion is to expand environment variables in `args`.  A related suggestion would be to provide a first-class DSL for config overrides.

Old:
```
 - uses: prepor/github-pulumi@master
   with:
     args: >
       up
       --config "gcp:project=${{ secrets.GCP_PROJECT }}"
       --config "image=gcr.io/${{ secrets.GCP_PROJECT }}/example/image:${{ github.sha }}"
```

New:
```
 - uses: prepor/github-pulumi@master
   with:
     args: up
     config:
       gcp:project: $GCP_PROJECT
       image: gcr.io/$GCP_PROJECT/example/image:${{ github.sha }}
```
